package Presentacion_Capa1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Telyman
 */

import Entidades.Cliente;
import Entidades.DetallesFactura;
import Entidades.DevolucionesVentas;
import Entidades.EncabezadoFactura;
import Entidades.OrdenesCompra;
import Entidades.Trabajador;
import LogicaNegocio_Capa2.LNCliente;
import LogicaNegocio_Capa2.LNDetalleFactura;
import LogicaNegocio_Capa2.LNDevolucionesVentas;
import LogicaNegocio_Capa2.LNEncabezadoFactura;
import LogicaNegocio_Capa2.LNOrdenesCompra;
import LogicaNegocio_Capa2.LNTrabajador;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

public class FrmDevolucionesVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDevolucionesVentas
     */
    private DevolucionesVentas GenerarEntidad(){
        //PONER AQUI SI FALTAN DATOSSSSSSSS
        
        Date fecha = new java.util.Date();
        Date fecha2 = new java.util.Date();
        fecha = DCFechaRealizacion.getDate();
        fecha2 = DCFechaFact.getDate();
      
        
        java.sql.Date sqlDate = new java.sql.Date(fecha.getTime());
        java.sql.Date sqlDate2 = new java.sql.Date(fecha2.getTime());
        
        DevolucionesVentas devoluciones = new DevolucionesVentas();
        if(!TxtNumDev.getText().equals("")){
            devoluciones.setExiste(true);
            devoluciones.setNumero_devolucion(Integer.parseInt(TxtNumDev.getText()));
        }
        devoluciones.setNumero_devolucion(Integer.parseInt(TxtNumDev.getText()));
        devoluciones.setNumero_factura(Integer.parseInt(TxtNumFact.getText()));
        devoluciones.setNumero_producto(Integer.parseInt(TxtNumP.getText()));
        devoluciones.setFecha_realizacion(sqlDate);
        devoluciones.setFecha_limite(sqlDate2);
        devoluciones.setMotivo_devolucion(TxtMotivo.getText());
        devoluciones.setAceptacion_devolucion(TxtAceptacion.getSelectedItem().toString());
        devoluciones.setId_trabajador(Integer.parseInt(TxtIdTrabajador.getText()));
        return devoluciones;
    }
    
       //VARIABLE GLOBAL
    DefaultTableModel modelo;
    private void LimpiarTabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TblDevolucion.setModel(modelo);
        modelo.addColumn("N° Devolución");
        modelo.addColumn("N° Factura");
        modelo.addColumn("N° Producto");
        modelo.addColumn("Fecha Realización");
        modelo.addColumn("Fecha Factura");
        modelo.addColumn("Motivo Devolución");
        modelo.addColumn("Aceptación Devolución");
        modelo.addColumn("ID Trabajador");
   
    }
    
      //Metodo para cargar los CLIENTES EN LA TABLA
    private void CargarDatos(String condicion) throws  Exception{
        try {
            LNDevolucionesVentas logica = new LNDevolucionesVentas();
            List<DevolucionesVentas> lista;
            LimpiarTabla();
            Object[] fila = new Object[8];
            lista = logica.ListarRegistros(condicion);
            for(DevolucionesVentas devoluciones:lista){
                fila[0] = devoluciones.getNumero_devolucion();
                fila[1] = devoluciones.getNumero_factura();
                fila[2] = devoluciones.getNumero_producto();
                fila[3] = devoluciones.getFecha_realizacion();
                fila[4] = devoluciones.getFecha_limite();
                fila[5] = devoluciones.getMotivo_devolucion();
                fila[6] = devoluciones.getAceptacion_devolucion();
                fila[7] = devoluciones.getId_trabajador();
                modelo.addRow(fila);
            }
            
        } catch (Exception e) {
            throw e;
        }
    }
    
    private void Limpiar(){
        TxtNumDev.setText("");
        //TxtNumFact.setText("");
        TxtMotivo.setText("");
        
        TxtIdTrabajador.setText("");
        
    }
    
    
    
    
    
    
    
    public FrmDevolucionesVentas() {
        initComponents();
        
          try {
            CargarDatos("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtNumDev = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNumFact = new javax.swing.JTextField();
        BtnBuscarFac = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DCFechaRealizacion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        DCFechaFact = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        TxtMotivo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtIdTrabajador = new javax.swing.JTextField();
        BtnBuscarTrabajador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDevolucion = new javax.swing.JTable();
        BtnLimpiar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnIngresar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TxtAceptacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TxtNumP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TxtGarantia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("N° Devolución");

        TxtNumDev.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumDevKeyTyped(evt);
            }
        });

        jLabel2.setText("N° Factura");

        TxtNumFact.setEditable(false);
        TxtNumFact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumFactKeyTyped(evt);
            }
        });

        BtnBuscarFac.setText("Buscar Factura");
        BtnBuscarFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarFacActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha Realización");

        jLabel4.setText("Fecha Factura");

        DCFechaFact.setEnabled(false);

        jLabel5.setText("Motivo Devolución");

        TxtMotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMotivoKeyTyped(evt);
            }
        });

        jLabel6.setText("Aceptación de Devolución");

        jLabel7.setText("Trabajador");

        TxtIdTrabajador.setEditable(false);
        TxtIdTrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtIdTrabajadorKeyTyped(evt);
            }
        });

        BtnBuscarTrabajador.setText("Buscar Trabajador");
        BtnBuscarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarTrabajadorActionPerformed(evt);
            }
        });

        TblDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDevolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDevolucionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblDevolucion);

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Mantenimiento de Devoluciones de Ventas");

        TxtAceptacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        jLabel9.setText("N° Producto");

        TxtNumP.setEditable(false);
        TxtNumP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumPActionPerformed(evt);
            }
        });
        TxtNumP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumPKeyTyped(evt);
            }
        });

        jButton1.setText("Buscar Fecha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Garantía");

        TxtGarantia.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtMotivo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtNumDev, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(TxtNumFact, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel10))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(TxtNumP, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TxtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(DCFechaRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3)))
                                        .addComponent(BtnBuscarFac))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton1)
                                        .addComponent(jLabel4)
                                        .addComponent(DCFechaFact, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(TxtAceptacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnBuscarTrabajador)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(177, 177, 177))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtNumDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtNumFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DCFechaRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DCFechaFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNumP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscarFac)
                    .addComponent(jButton1))
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TxtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarTrabajador)
                    .addComponent(TxtAceptacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnModificar)
                    .addComponent(BtnIngresar)
                    .addComponent(BtnBuscar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed

        // TODO add your handling code here:
        if (TxtNumDev.getText().equals("") || TxtNumFact.getText().equals("")  || TxtMotivo.getText().equals("") || TxtIdTrabajador.getText().equals("") || DCFechaFact.getDate().equals("") /*|| TxtPrecioC.getText().equals("")*/ || DCFechaRealizacion.getDate().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe insertar datos");
        } else {
            LNDevolucionesVentas logica = new LNDevolucionesVentas();
            DevolucionesVentas devoluciones = GenerarEntidad();
            try {
                if((logica.VerificarIns(devoluciones))==1  || (logica.VerificarFecha(devoluciones))==1 || (logica.VerificarIng2(devoluciones))==1 ) {
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                } else if(TxtGarantia.getText().equals("No Aplica")){
                    JOptionPane.showMessageDialog(this, "Este producto no tiene garantia");
                }
               else{
                    logica.Insertar(devoluciones);
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                }
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            try {
                Limpiar();
                CargarDatos("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

          
         
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void TblDevolucionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDevolucionMouseClicked
        // TODO add your handling code here:
         try {
            LNDevolucionesVentas logica = new LNDevolucionesVentas();
            DevolucionesVentas devoluciones;
            String condicion;
            
            if(evt.getClickCount() == 2){
                int fila = TblDevolucion.rowAtPoint(evt.getPoint());
                TxtNumDev.setText(TblDevolucion.getValueAt(fila, 0).toString());
                condicion = String.format("numero_devolucion = %s", TxtNumDev.getText());
                devoluciones = logica.ObtenerRegistro(condicion);
                
                TxtNumDev.setText(String.valueOf(devoluciones.getNumero_devolucion()));
                TxtNumFact.setText(String.valueOf(devoluciones.getNumero_factura()));
                TxtNumP.setText(String.valueOf(devoluciones.getNumero_producto()));
                DCFechaRealizacion.setDate(java.sql.Date.valueOf(devoluciones.getFecha_realizacion().toString()));
                DCFechaFact.setDate(java.sql.Date.valueOf(devoluciones.getFecha_limite().toString()));
                TxtMotivo.setText(devoluciones.getMotivo_devolucion());
                TxtAceptacion.setSelectedItem(devoluciones.getAceptacion_devolucion());
                TxtIdTrabajador.setText(String.valueOf(devoluciones.getId_trabajador()));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_TblDevolucionMouseClicked

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
                if (TxtNumDev.getText().equals("") || TxtNumFact.getText().equals("")  || TxtMotivo.getText().equals("") || TxtIdTrabajador.getText().equals("") || DCFechaFact.getDate().equals("") /*|| TxtPrecioC.getText().equals("")*/ || DCFechaRealizacion.getDate().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una devolución para poder modificarla");
        } else {
            LNDevolucionesVentas logica = new LNDevolucionesVentas();
            DevolucionesVentas devoluciones = GenerarEntidad();
            try {
                
                if((logica.VerificarMod(devoluciones))==1 || (logica.VerificarExiste(devoluciones))==1){
                     JOptionPane.showMessageDialog(this, logica.getMensaje());
                }else{
                     logica.Modificar(devoluciones);
                JOptionPane.showMessageDialog(this, logica.getMensaje());
                }
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            try {
                CargarDatos("");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
                if (TxtNumDev.getText().equals("") || TxtNumFact.getText().equals("") || TxtMotivo.getText().equals("") || TxtIdTrabajador.getText().equals("") || DCFechaFact.getDate().equals("") /*|| TxtPrecioC.getText().equals("")*/ || DCFechaRealizacion.getDate().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una devolución para poder eliminarla");
        } else {
            LNDevolucionesVentas logica = new LNDevolucionesVentas();
            DevolucionesVentas devoluciones = GenerarEntidad();
            try {
                if((logica.VerificarEliminar(devoluciones))==1 || (logica.VerificarExiste(devoluciones))==1){
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                }else{
                    logica.Eliminar(devoluciones);
                JOptionPane.showMessageDialog(this, logica.getMensaje());
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            try {
                CargarDatos("");
                Limpiar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        FrmBuscarDevolucion buscar = new FrmBuscarDevolucion(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    LNDevolucionesVentas logica = new LNDevolucionesVentas();
                    DevolucionesVentas devoluciones;
                    if (id > -1) {
                        condicion = String.format("numero_devolucion = %s", id);
                        devoluciones = logica.ObtenerRegistro(condicion);

                        TxtNumDev.setText(String.valueOf(devoluciones.getNumero_devolucion()));
                        TxtNumFact.setText(String.valueOf(devoluciones.getNumero_factura()));
                        TxtNumP.setText(String.valueOf(devoluciones.getNumero_producto()));
                        DCFechaRealizacion.setDate(java.sql.Date.valueOf(devoluciones.getFecha_realizacion().toString()));
                        DCFechaFact.setDate(java.sql.Date.valueOf(devoluciones.getFecha_limite().toString()));
                        TxtMotivo.setText(devoluciones.getMotivo_devolucion());
                        TxtAceptacion.setSelectedItem(devoluciones.getAceptacion_devolucion());
                        TxtIdTrabajador.setText(String.valueOf(devoluciones.getId_trabajador()));
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
       buscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void TxtNumDevKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumDevKeyTyped
        // TODO add your handling code here:
             char c = evt.getKeyChar();
     if( c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtNumDevKeyTyped

    private void TxtNumFactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumFactKeyTyped
        // TODO add your handling code here:
             char c = evt.getKeyChar();
     if( c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtNumFactKeyTyped

    private void TxtIdTrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdTrabajadorKeyTyped
        // TODO add your handling code here:
             char c = evt.getKeyChar();
     if( c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtIdTrabajadorKeyTyped

    private void TxtMotivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMotivoKeyTyped
        // TODO add your handling code here:
        SoloLetras(evt);
    }//GEN-LAST:event_TxtMotivoKeyTyped

    private void BtnBuscarFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarFacActionPerformed
        // TODO add your handling code here:
         FrmBuscarDetalle buscar = new FrmBuscarDetalle(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    int id2 = buscar.ObtenerId2();
                    String condicion = "";
                    LNDetalleFactura logica = new LNDetalleFactura();
                    DetallesFactura encabezado;
                    if (id > -1) {
                        condicion = String.format("numero_producto = %d and numero_factura = %d", id,id2); //d es para enteros
                        encabezado = logica.ObtenerRegistro(condicion);

                        TxtNumFact.setText(String.valueOf(encabezado.getNumero_factura()));
                        TxtNumP.setText(String.valueOf(encabezado.getNumero_producto()));
                        TxtGarantia.setText(String.valueOf(encabezado.getGarantia())); 
                      
                        
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
        buscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarFacActionPerformed

    private void BtnBuscarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarTrabajadorActionPerformed
        // TODO add your handling code here:
         FrmBuscarTrabajador buscar = new FrmBuscarTrabajador(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    LNTrabajador logica = new LNTrabajador();
                    Trabajador cliente;
                    if (id > -1) {
                        condicion = String.format("id_trabajador = %d", id); //d es para enteros
                        cliente = logica.ObtenerRegistro(condicion);
                        TxtIdTrabajador.setText(String.valueOf(cliente.getId_trabajador()));
                        
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
       buscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarTrabajadorActionPerformed

    private void TxtNumPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumPKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmBuscarEncabezado buscar = new FrmBuscarEncabezado(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    LNEncabezadoFactura logica = new LNEncabezadoFactura();
                    EncabezadoFactura cliente;
                    if (id > -1) {
                        condicion = String.format("numero_factura = %d", id); //d es para enteros
                        cliente = logica.ObtenerRegistro(condicion);
                        DCFechaFact.setDate(java.sql.Date.valueOf(cliente.getFecha().toString()));
                        
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
       buscar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtNumPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucionesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucionesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucionesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDevolucionesVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDevolucionesVentas().setVisible(true);
            }
        });
    }
    
        
//     char c = evt.getKeyChar();
//     if( c<'0' || c > '9') evt.consume();
//    
//    char c = evt.getKeyChar();
//    if( (c<'0' || c > '9') && (c!='.') ) evt.consume();
//    
         public void SoloLetras(KeyEvent evt){
        char s;
        s= evt.getKeyChar();
        if(!Character.isLetter(s) && s != KeyEvent.VK_SPACE ){
            evt.consume();
        }
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnBuscarFac;
    private javax.swing.JButton BtnBuscarTrabajador;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private com.toedter.calendar.JDateChooser DCFechaFact;
    private com.toedter.calendar.JDateChooser DCFechaRealizacion;
    private javax.swing.JTable TblDevolucion;
    private javax.swing.JComboBox<String> TxtAceptacion;
    private javax.swing.JTextField TxtGarantia;
    private javax.swing.JTextField TxtIdTrabajador;
    private javax.swing.JTextField TxtMotivo;
    private javax.swing.JTextField TxtNumDev;
    private javax.swing.JTextField TxtNumFact;
    private javax.swing.JTextField TxtNumP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
