/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion_Capa1;

import Entidades.DetallesFactura;
import Entidades.EncabezadoFactura;
import LogicaNegocio_Capa2.LNDetalleFactura;
import LogicaNegocio_Capa2.LNEncabezadoFactura;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Telyman
 */
public class FrmDetalleFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDetalleFactura
     */
             private DetallesFactura  GenerarEntidad(){
        //PONER AQUI SI FALTAN DATOSSSSSSSS
        
        DetallesFactura factura = new DetallesFactura();
        
        
        
       
        factura.setNumero_factura(Integer.parseInt(TxtNumF.getText()));
        factura.setNumero_producto(Integer.parseInt(TxtNumP.getText()));
        factura.setNombre_producto(TxtNomp.getText());
        factura.setCantidad(Integer.parseInt(TxtCant.getText()));
        factura.setGarantia(TxtGarantia.getText());
       
        
        
        return factura;
    }
     //VARIABLE GLOBAL
    DefaultTableModel modelo;
    private void LimpiarTabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TblDetalle.setModel(modelo);
        modelo.addColumn("Factura N°");
        modelo.addColumn("Producto N°");
        modelo.addColumn("Cantidad Comprada");
        modelo.addColumn("Nombre Producto");
        modelo.addColumn("Garantía");
        
   
    }
        private void CargarDatos(String condicion) throws  Exception{
        try {
            LNDetalleFactura logica = new LNDetalleFactura();
            List<DetallesFactura> lista;
            LimpiarTabla();
            Object[] fila = new Object[5];
            lista = logica.ListarRegistros(condicion);
            for(DetallesFactura factura:lista){
                fila[0] = factura.getNumero_factura();
                fila[1] = factura.getNumero_producto();
                fila[2] = factura.getCantidad();
                fila[3] = factura.getNombre_producto();
                fila[4] = factura.getGarantia();
               
                modelo.addRow(fila);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
        
    private void Limpiar(){
        TxtNumF.setText("");
        TxtNumP.setText("");
        TxtCant.setText("");
        TxtNomp.setText("");
        TxtGarantia.setText("");
       
       
    }
    
    
    
    
    
    
    
    
    
    public FrmDetalleFactura() {
        initComponents();
        
        try {
            CargarDatos("");
        } catch (Exception e) {
              JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblDetalle = new javax.swing.JTable();
        E = new javax.swing.JButton();
        M = new javax.swing.JButton();
        TxtNumP = new javax.swing.JTextField();
        B = new javax.swing.JButton();
        TxtGarantia = new javax.swing.JTextField();
        TxtNomp = new javax.swing.JTextField();
        I = new javax.swing.JButton();
        TxtCant = new javax.swing.JTextField();
        TxtNumF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel9.setText("Garantía");

        TblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDetalleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblDetalle);

        E.setText("Eliminar");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });

        M.setText("Modificar");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });

        TxtNumP.setEditable(false);

        B.setText("Buscar");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        TxtGarantia.setEditable(false);

        TxtNomp.setEditable(false);

        I.setText("Salir");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });

        TxtCant.setEditable(false);

        TxtNumF.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Mantenimiento de Detalle de Factura");

        jLabel2.setText("Factura N°");

        jLabel4.setText("Cantidad Comprada");

        jLabel5.setText("Nombre Producto:");

        jLabel6.setText("Producto N°");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(I)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(M)
                                .addGap(18, 18, 18)
                                .addComponent(E))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtNumF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(TxtNumP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(TxtNomp, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(208, 208, 208))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNumF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNumP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(I)
                    .addComponent(E)
                    .addComponent(M)
                    .addComponent(B)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TblDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDetalleMouseClicked
        // TODO add your handling code here:
        try {
            LNDetalleFactura logica = new LNDetalleFactura();
            DetallesFactura detalle;
            String condicion;

            if(evt.getClickCount() == 2){
                int fila = TblDetalle.rowAtPoint(evt.getPoint());
                TxtNumF.setText(TblDetalle.getValueAt(fila, 0).toString());
                TxtNumP.setText(TblDetalle.getValueAt(fila,1).toString());
                condicion = String.format("numero_factura = %s and numero_producto = %s", TxtNumF.getText(),TxtNumP.getText());
                detalle = logica.ObtenerRegistro(condicion);
                
                
                TxtNumF.setText(String.valueOf(detalle.getNumero_factura()));
                TxtNumP.setText(String.valueOf(detalle.getNumero_producto()));
                TxtCant.setText(String.valueOf(detalle.getCantidad()));
                TxtNomp.setText(detalle.getNombre_producto());
                TxtGarantia.setText(detalle.getGarantia());
               
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_TblDetalleMouseClicked

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
        if (TxtCant.getText().equals("") || TxtGarantia.getText().equals("") || TxtNumP.getText().equals("") || TxtNomp.getText().equals("") || TxtNumF.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un detalle de factura para eliminarlo");
        } else {
            LNDetalleFactura logica = new LNDetalleFactura();
            DetallesFactura factura = GenerarEntidad();
            try {
                logica.Eliminar(factura);
                JOptionPane.showMessageDialog(this, logica.getMensaje());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            try {
                CargarDatos("");
                Limpiar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_EActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        // TODO add your handling code here:
         if (TxtCant.getText().equals("") || TxtGarantia.getText().equals("") || TxtNumP.getText().equals("") || TxtNomp.getText().equals("") || TxtNumF.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un detalle de factura para modificarlo");
        } else {
            LNDetalleFactura logica = new LNDetalleFactura();
            DetallesFactura factura = GenerarEntidad();
            try {
                if((logica.VerificarMod(factura))==1){
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                }else{
                    logica.Modificar(factura);
                JOptionPane.showMessageDialog(this, logica.getMensaje());
                }
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            try {
                CargarDatos("");
                Limpiar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_MActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
        FrmBuscarDetalle buscar = new FrmBuscarDetalle(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    int id2 = buscar.ObtenerId2();
                    String condicion = "";
                    LNDetalleFactura logica = new LNDetalleFactura();
                    DetallesFactura encabezado;
                    if (id > -1 && id2 > -1) {
                        condicion = String.format("numero_producto = %d and numero_factura = %d", id, id2); //d es para enteros
                        encabezado = logica.ObtenerRegistro(condicion);

                        TxtNumF.setText(String.valueOf(encabezado.getNumero_factura()));
                        TxtNumP.setText(String.valueOf(encabezado.getNumero_producto()));
                        TxtCant.setText(String.valueOf( encabezado.getCantidad()));
                        TxtNomp.setText(encabezado.getNombre_producto());
                        TxtGarantia.setText(encabezado.getGarantia());
                        
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
        buscar.setVisible(true);
    }//GEN-LAST:event_BActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        // TODO add your handling code here:
        //         FrmFactura formularioInterno = new FrmFactura();
        //        formularioInterno.show();
        dispose();

    }//GEN-LAST:event_IActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B;
    private javax.swing.JButton E;
    private javax.swing.JButton I;
    private javax.swing.JButton M;
    private javax.swing.JTable TblDetalle;
    private javax.swing.JTextField TxtCant;
    private javax.swing.JTextField TxtGarantia;
    private javax.swing.JTextField TxtNomp;
    private javax.swing.JTextField TxtNumF;
    private javax.swing.JTextField TxtNumP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
