/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion_Capa1;

import Entidades.Cliente;
import Entidades.DetallesFactura;
import Entidades.EncabezadoFactura;
import Entidades.Producto;
import Entidades.Proveedor;
import Entidades.Trabajador;
import LogicaNegocio_Capa2.LNCliente;
import LogicaNegocio_Capa2.LNDetalleFactura;
import LogicaNegocio_Capa2.LNEncabezadoFactura;
import LogicaNegocio_Capa2.LNProducto;
import LogicaNegocio_Capa2.LNProovedor;
import LogicaNegocio_Capa2.LNTrabajador;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javafx.scene.effect.GaussianBlurBuilder;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Telyman
 */
public class FrmFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmFactura
     */
        private EncabezadoFactura GenerarEntidad(){
        //PONER AQUI SI FALTAN DATOSSSSSSSS
        
        EncabezadoFactura factura = new EncabezadoFactura();
        
        Date fecha = new Date();
        fecha = DCFechaFact.getDate();
        java.sql.Date sqlDate = new java.sql.Date(fecha.getTime());
        
       
        factura.setNumero_factura(Integer.parseInt(TxtNumFac.getText()));
        factura.setId_trabajador(Integer.parseInt(TxtIdTrabajador.getText()));
        factura.setFecha(sqlDate);
        //factura.setSubtotal(Float.parseFloat(TxtSubtotal.getText()));
        factura.setImpuesto(Float.parseFloat(TxtImpuesto.getText()));
       // factura.setDescuento(Integer.parseInt(TxtDesc.getText()));
        factura.setMonto_a_pagar(Float.parseFloat(TxtMontoPagar.getText()));
        factura.setId_cliente(Integer.parseInt(TxtIdClient.getText()));
        
        
        return factura;
    }
        
         private DetallesFactura  GenerarEntidad2(){
        //PONER AQUI SI FALTAN DATOSSSSSSSS
        
        DetallesFactura factura = new DetallesFactura();
        
        
        
       
        factura.setNumero_factura(Integer.parseInt(TxtNumFac.getText()));
        factura.setNumero_producto(Integer.parseInt(TxtNumProducto.getText()));
        factura.setNombre_producto(TxtNombrePro.getText());
        factura.setCantidad(Integer.parseInt(TxtCantidad.getValue().toString()));
        factura.setGarantia(TxtGarantia.getSelectedItem().toString());
       
        
        
        return factura;
    }
    
    
    
    
    
    
    public FrmFactura() {
        initComponents();
        this.setTitle("Sistema de Factura");
        
             Calendar c2 = new GregorianCalendar();
             DCFechaFact.setCalendar(c2);
             
             LimpiarTabla();
             
                 float imp = 13;
           //CargarDatos("");
            TxtImpuesto.setText(""+ imp);
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtMontoPagar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtIdTrabajador = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblAgregar = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TxtNumFac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtIdClient = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtSubtotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtNumProducto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtNombrePro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DCFechaFact = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BtnAgregarProducto = new javax.swing.JButton();
        TxtCantidad = new javax.swing.JSpinner();
        TxtGarantia = new javax.swing.JComboBox<>();
        BtnBuscarP = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TxtImpuesto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMA DE FACTURA PARA TIENDA DEPORTIVA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Venta de Productos Deportivos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Teléfono: 2450-0301");

        jLabel10.setText("Monto a Pagar:");

        jLabel16.setText("ID Trabajador:");

        TxtIdTrabajador.setEditable(false);

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TblAgregar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblAgregarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblAgregar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Factura N° :");

        TxtNumFac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumFacKeyTyped(evt);
            }
        });

        jLabel5.setText("ID_Cliente:");

        TxtIdClient.setEditable(false);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio:");

        TxtSubtotal.setEditable(false);

        jLabel11.setText("Producto N°:");

        TxtNumProducto.setEditable(false);

        jLabel12.setText("Nombre Producto:");

        TxtNombrePro.setEditable(false);

        jLabel13.setText("Stock:");

        TxtStock.setEditable(false);

        jLabel6.setText("Fecha:");

        DCFechaFact.setEnabled(false);
        DCFechaFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DCFechaFactMouseClicked(evt);
            }
        });

        jLabel15.setText("Garantía:");

        jLabel14.setText("Cantidad:");

        BtnAgregarProducto.setText("Agregar Producto");
        BtnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarProductoActionPerformed(evt);
            }
        });

        TxtGarantia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aplica", "No Aplica" }));
        TxtGarantia.setEnabled(false);

        BtnBuscarP.setText("Buscar Producto");
        BtnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAgregarProducto)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel14))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DCFechaFact, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(TxtIdClient)
                            .addComponent(TxtCantidad)
                            .addComponent(TxtNumFac))
                        .addGap(13, 13, 13)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(BtnBuscarP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtStock)
                            .addComponent(TxtNombrePro)
                            .addComponent(TxtNumProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtNumFac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(TxtNumProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel12)
                    .addComponent(TxtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TxtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBuscarP)
                            .addComponent(DCFechaFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnAgregarProducto)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jButton2.setText("Generar Factura");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Impuesto:");

        TxtImpuesto.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setText("Los productos incluyen el I.V.A y su descuento (si es aplicable)");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(81, 81, 81)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(12, 12, 12)
                                .addComponent(TxtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addComponent(TxtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(TxtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnBuscar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(TxtMontoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(TxtImpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DCFechaFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DCFechaFactMouseClicked
        // TODO add your handling code here:
//         Date fecha = new Date();
//         
//          DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
//         
//       DCFechaFact.getDate();
    }//GEN-LAST:event_DCFechaFactMouseClicked

    DefaultTableModel modelo = new DefaultTableModel();
      private void LimpiarTabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TblAgregar.setModel(modelo);
        modelo.addColumn("N° Factura");
        modelo.addColumn("N° Producto");
        modelo.addColumn("Nombre Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
       // modelo.addColumn("Impuesto");
        //modelo.addColumn("Descuento");
        modelo.addColumn("Garantía");
        
       
   
    }
    
    private void BtnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarProductoActionPerformed
        // TODO add your handling code here:
         if (TxtNumFac.getText().equals("") || TxtNumProducto.getText().equals("") || TxtCantidad.getValue().equals(0)){
             JOptionPane.showMessageDialog(this, "Faltan datos");
         }else{
             agregarProducto();
         }
        
        
      
        
    }//GEN-LAST:event_BtnAgregarProductoActionPerformed
//GENERAR VENTA AQUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (TxtNumFac.getText().equals("") || TxtNumProducto.getText().equals("") || TxtCantidad.getValue().equals(0)|| TxtIdClient.getText().equals("")|| TxtIdTrabajador.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Faltan datos");
         }else{
               guardarFactura();
                guardarDetalleFactura();
         }
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblAgregarMouseClicked
        // TODO add your handling code here:
        //String espacio = "";
        if (evt.getClickCount() == 2) {
            if (TblAgregar.getSelectedRow() != -1) {
                modelo.removeRow(TblAgregar.getSelectedRow());
            }

            TxtSubtotal.setText("");
            TxtNumProducto.setText("");
            TxtNombrePro.setText("");
            TxtStock.setText("");
            calcularTotal();
            //TxtMontoPagar.setText("");
        }
      
        
        
        
    }//GEN-LAST:event_TblAgregarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmBuscarCliente buscar = new FrmBuscarCliente(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    LNCliente logica = new LNCliente();
                    Cliente cliente;
                    if (id > -1) {
                        condicion = String.format("id_cliente = %s", id);
                        cliente = logica.ObtenerRegistro(condicion);
                        
                        TxtIdClient.setText(Integer.toString(cliente.getId_cliente()));
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
       buscar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarPActionPerformed
        // TODO add your handling code here:
        FrmBuscarProducto buscar = new FrmBuscarProducto(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    LNProducto logica = new LNProducto();
                    Producto producto;
                    if (id > -1) {
                        condicion = String.format("numero_producto = %s", id);
                        producto = logica.ObtenerRegistro(condicion);
                        
                        TxtNumProducto.setText(Integer.toString(producto.getNumero_producto()));
                        TxtNombrePro.setText(producto.getNombre_producto());
                        TxtStock.setText(Integer.toString(producto.getCantidad()));
                        TxtGarantia.setSelectedItem(producto.getGarantia());
                        TxtSubtotal.setText(Float.toString(producto.getPrecio_total()));
                        //TxtImpuesto.setText(Float.toString(producto.getImpuesto()));
                        //TxtDesc.setText(Float.toString(producto.getDescuento()));
                        
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
       buscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarPActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        FrmBuscarTrabajador buscar = new FrmBuscarTrabajador(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    LNTrabajador logica = new LNTrabajador();
                    Trabajador trabajador;
                    if (id > -1) {
                        condicion = String.format("id_trabajador = %s", id);
                        trabajador = logica.ObtenerRegistro(condicion);
                        
                        TxtIdTrabajador.setText(Integer.toString(trabajador.getId_trabajador()));
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
       buscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtNumFacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumFacKeyTyped
        // TODO add your handling code here:
       char c = evt.getKeyChar();
        if(c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtNumFacKeyTyped
   
 
    
    void Limpiar(){
       //TxtNumFac.setText("");
       TxtIdClient.setText("");
       //TxtPrecioFactura.setText("");
       //TxtImpuesto.setText("");
       //TxtDesc.setText("");
       TxtSubtotal.setText("");
       TxtNumProducto.setText("");
       TxtNombrePro.setText("");
       TxtStock.setText("");
       TxtMontoPagar.setText("");
   
   } 
    void guardarFactura(){
        int numFact= Integer.parseInt(TxtNumFac.getText());
        int idT = Integer.parseInt(TxtIdTrabajador.getText());
        Date fecha = new Date();
        fecha = DCFechaFact.getDate();
        java.sql.Date sqlDate = new java.sql.Date(fecha.getTime());
        //int subtotal = Integer.parseInt( TxtPrecioFactura.getText());
        Float impuesto = Float.parseFloat(TxtImpuesto.getText());
        //Float descuento = Float.parseFloat(TxtDesc.getText());
        Float montoTotal = Float.parseFloat(TxtMontoPagar.getText());
        int id_c = Integer.parseInt(TxtIdClient.getText());
        EncabezadoFactura fac = new EncabezadoFactura();
        
        fac.setNumero_factura(numFact);
        fac.setId_trabajador(idT);
        fac.setFecha(sqlDate);
        //fac.setSubtotal(subtotal);
        fac.setImpuesto(impuesto);
        //fac.setDescuento(descuento);
        fac.setMonto_a_pagar(montoTotal);
        fac.setId_cliente(id_c);
        
        LNEncabezadoFactura logica = new LNEncabezadoFactura();
       
        
        
       
            try {
                
                if ((logica.VerificarIns(fac)) == 1) {
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                }
                else {
                    logica.Insertar(fac);
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        
        
        
        
        
        
        
    
        
    }
    
    
    
    void guardarDetalleFactura(){
        DetallesFactura dF = new DetallesFactura();
        LNDetalleFactura logicaD = new LNDetalleFactura();
        
         Date fecha = new Date();
        fecha = DCFechaFact.getDate();
        //java.sql.Date sqlDate = new java.sql.Date(fecha.getTime());
        
        for (int i = 0; i < TblAgregar.getRowCount(); i++) {
            int idF = Integer.parseInt(TblAgregar.getValueAt(i, 0).toString());
            int idP = Integer.parseInt(TblAgregar.getValueAt(i, 1).toString());
            String nomP = TblAgregar.getValueAt(i, 2).toString();
            int cant = Integer.parseInt(TblAgregar.getValueAt(i, 3).toString());
            String garantia = TblAgregar.getValueAt(i, 5).toString();

            dF.setNumero_factura(idF);
            dF.setNumero_producto(idP);
            dF.setNombre_producto(nomP);
            dF.setCantidad(cant);
            dF.setGarantia(garantia);
            
            try {
                if((logicaD.VerificarIns(dF))==1){
                    JOptionPane.showMessageDialog(this, logicaD.getMensaje());
                }else{
                    logicaD.Insertar(dF);
                   
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
  
            
            
        }
       
        
    
    }
    
    
    
    
    
    
    
    
    Producto p = new Producto();
    EncabezadoFactura f = new EncabezadoFactura();
    int idP=0;
    int idF =0;
    String nomp="";
    int cantidad=0;
    Date fecha = new Date();
    
    int cant;
    Float precio;
    Float impuesto;
    Float descuento;
    
    int cont =0;
    void agregarProducto(){
        cont ++;
        float Total;
        int item =0;
        modelo = (DefaultTableModel)TblAgregar.getModel();
        item = item +1;
        idF = Integer.parseInt(TxtNumFac.getText());
        idP = Integer.parseInt(TxtNumProducto.getText());
        nomp = TxtNombrePro.getText();
       
        
        
        
        cantidad = Integer.parseInt(TxtCantidad.getValue().toString());
        Float precio = Float.parseFloat(TxtSubtotal.getText());
        //Float impuesto = Float.parseFloat(TxtImpuesto.getText());
        //int descuento = Integer.parseInt(TxtDesc.getText());
        String garantia = TxtGarantia.getSelectedItem().toString();
        
        int stock = Integer.parseInt(TxtStock.getText());
        ArrayList lista = new ArrayList();
        if(stock < 0 || cantidad>stock){
        
           JOptionPane.showMessageDialog(this, "No hay producto suficientes o no puede comprar tantos productos");
            
        }else{
            
            
             lista.add(item);
            lista.add(idF);
            lista.add(idP);
            lista.add(nomp);
            lista.add(cantidad);
            lista.add(precio);
            //lista.add(impuesto);
            //lista.add(descuento);
            lista.add(garantia);
           
            
            Object[] ob = new Object[6];
            ob[0] = lista.get(1);
            ob[1] = lista.get(2);
            ob[2] = lista.get(3);
            ob[3] = lista.get(4);
            ob[4] = lista.get(5);
            ob[5] = lista.get(6);
         
            modelo.addRow(ob);
          TblAgregar.setModel(modelo);
          calcularTotal();
        }
        
      

 
        
      
    
    }
    
    void calcularTotal(){
        float totalPagar =0;
        try {
             
            for (int i = 0; i < TblAgregar.getRowCount(); i++) {
                
                cant = Integer.parseInt(TblAgregar.getValueAt(i, 3).toString());
                precio = Float.parseFloat(TblAgregar.getValueAt(i, 4).toString());
                //impuesto = Float.parseFloat(TblAgregar.getValueAt(i, 5).toString());
                //descuento = Float.parseFloat(TblAgregar.getValueAt(i, 6).toString());

                float subTotal = cant * precio; //2000
               
                totalPagar = totalPagar+  subTotal;
                //subtotalTotal = subTotal;  
                
               
            }
             TxtMontoPagar.setText("" + totalPagar);
            //TxtPrecioFactura.setText(""+ subtotalTotal2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

               
        
    }
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarProducto;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnBuscarP;
    private com.toedter.calendar.JDateChooser DCFechaFact;
    private javax.swing.JTable TblAgregar;
    private javax.swing.JSpinner TxtCantidad;
    private javax.swing.JComboBox<String> TxtGarantia;
    private javax.swing.JTextField TxtIdClient;
    private javax.swing.JTextField TxtIdTrabajador;
    private javax.swing.JTextField TxtImpuesto;
    private javax.swing.JTextField TxtMontoPagar;
    private javax.swing.JTextField TxtNombrePro;
    private javax.swing.JTextField TxtNumFac;
    private javax.swing.JTextField TxtNumProducto;
    private javax.swing.JTextField TxtStock;
    private javax.swing.JTextField TxtSubtotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
