package Presentacion_Capa1;

import Entidades.Producto;
import Entidades.Proveedor;
import LogicaNegocio_Capa2.LNProducto;
import LogicaNegocio_Capa2.LNProovedor;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Telyman
 */
public class FrmProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmProducto
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
      private Producto GenerarEntidad(){
        //PONER AQUI SI FALTAN DATOSSSSSSSS
        
        Producto producto = new Producto();
        if(!TxtNumProducto.getText().equals("")){
            producto.setExiste(true);
            producto.setNumero_producto(Integer.parseInt(TxtNumProducto.getText()));
        }
        producto.setNumero_producto(Integer.parseInt(TxtNumProducto.getText()));
        producto.setNombre_producto(TxtNombreProducto.getText());
        producto.setTipo_producto(TxtTipoP.getSelectedItem().toString());
        producto.setPrecio_compra(Float.parseFloat(TxtPrecioC.getText()));
        producto.setPrecio_venta(Float.parseFloat(TxtPrecioV.getText()));
        producto.setCantidad(Integer.parseInt(TxtCant.getText()));
        producto.setImpuesto(Float.parseFloat(TxtImp.getText()));
        producto.setDescuento(Float.parseFloat(TxtDesc.getText()));
        producto.setDescripcion(TxtDescripcion.getText());
        producto.setGarantia(TxtGrantia.getSelectedItem().toString());
        producto.setPrecio_total(Float.parseFloat(TxtPTotal.getText()));
        producto.setDisponibilidad(Txtdisponibili.getSelectedItem().toString());
        producto.setNum_proveedor(Integer.parseInt(TxtNumProv.getText()));
        
        
        
        return producto;
    }
       //VARIABLE GLOBAL
    DefaultTableModel modelo;
    private void LimpiarTabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TblProducto.setModel(modelo);
        modelo.addColumn("Producto N°");
        modelo.addColumn("Nombre Producto");
        modelo.addColumn("Categoría");
        modelo.addColumn("Precio Compra");
        modelo.addColumn("Precio Venta");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Impuesto");
        modelo.addColumn("Descuento");
        modelo.addColumn("Descripción");
        modelo.addColumn("Garantía");
        modelo.addColumn("Disponibilidad");
        modelo.addColumn("Precio Total");
        modelo.addColumn("Proovedor N°");
   
    }
     //Metodo para cargar los CLIENTES EN LA TABLA
    private void CargarDatos(String condicion) throws  Exception{
        try {
            LNProducto logica = new LNProducto();
            List<Producto> lista;
            LimpiarTabla();
            Object[] fila = new Object[13];
            lista = logica.ListarRegistros(condicion);
            for(Producto producto:lista){
                fila[0] = producto.getNumero_producto();
                fila[1] = producto.getNombre_producto();
                fila[2] = producto.getTipo_producto();
                fila[3] = producto.getPrecio_compra();
                fila[4] = producto.getPrecio_venta();
                fila[5] = producto.getCantidad();
                fila[6] = producto.getImpuesto();
                fila[7] = producto.getDescuento();
                fila[8] = producto.getDescripcion();
                fila[9] = producto.getGarantia();
                fila[10] = producto.getDisponibilidad();
                fila[11] = producto.getPrecio_total();
                fila[12] = producto.getNum_proveedor();
                
                
                modelo.addRow(fila);
            }
            
        } catch (Exception e) {
            throw e;
        }
    }
    
    private void Limpiar(){
        TxtNombreProducto.setText("");
        TxtNombreProducto.setText("");
        TxtPrecioV.setText("");
        TxtCant.setText("");
        TxtImp.setText("");
        TxtDesc.setText("");
        TxtDescripcion.setText("");
        TxtNumProv.setText("");
        TxtPrecioC.setText("");
        TxtPTotal.setText("");
        TxtNumProducto.setText("");
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNumProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtPrecioC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtPrecioV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtCant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtImp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtDesc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtDescripcion = new javax.swing.JTextField();
        BtnLimpiar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnIngresar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        TxtTipoP = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        TxtNumProv = new javax.swing.JTextField();
        BtnBuscarProv = new javax.swing.JButton();
        Txtdisponibili = new javax.swing.JComboBox<>();
        TxtGrantia = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        TxtPTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TxtNumProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumProductoKeyTyped(evt);
            }
        });

        jLabel2.setText("Nombre Producto");

        TxtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNombreProductoKeyTyped(evt);
            }
        });

        jLabel3.setText("Categoria");

        jLabel4.setText("Precio Compra");

        TxtPrecioC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrecioCKeyTyped(evt);
            }
        });

        TblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblProducto);

        jLabel1.setText("N° Producto");

        jLabel6.setText("Precio Venta");

        TxtPrecioV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TxtPrecioVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtPrecioVMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtPrecioVMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TxtPrecioVMouseReleased(evt);
            }
        });
        TxtPrecioV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrecioVActionPerformed(evt);
            }
        });
        TxtPrecioV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrecioVKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPrecioVKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrecioVKeyTyped(evt);
            }
        });

        jLabel7.setText("Cantidad");

        TxtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCantKeyTyped(evt);
            }
        });

        jLabel8.setText("Impuesto");

        TxtImp.setEditable(false);
        TxtImp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtImpKeyTyped(evt);
            }
        });

        jLabel9.setText("Descuento");

        TxtDesc.setEditable(false);
        TxtDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDescKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDescKeyTyped(evt);
            }
        });

        jLabel10.setText("Garantía");

        jLabel11.setText("Disponibilidad");

        jLabel5.setText("Descripción");

        TxtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDescripcionKeyTyped(evt);
            }
        });

        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        TxtTipoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camisas", "Tennis", "Pantalonetas", "Artículos de Fútbol", "Artículos de Boxéo", " " }));

        jLabel12.setText("N°Proveedor");

        TxtNumProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumProvKeyTyped(evt);
            }
        });

        BtnBuscarProv.setText("Buscar Proveedor");
        BtnBuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarProvActionPerformed(evt);
            }
        });

        Txtdisponibili.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No Disponible" }));

        TxtGrantia.setEditable(true);
        TxtGrantia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aplica", "No Aplica" }));
        TxtGrantia.setEnabled(false);
        TxtGrantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGrantiaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Mantenimiento de Productos");

        jLabel14.setText("Precio Total");

        TxtPTotal.setEditable(false);
        TxtPTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPTotalKeyTyped(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(228, 228, 228))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(TxtDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TxtPrecioC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtImp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtPTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtGrantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(Txtdisponibili, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtNumProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTipoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnBuscarProv)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(TxtNumProv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TxtCant, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNumProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNombreProducto)
                            .addComponent(TxtTipoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNumProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBuscarProv)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtPrecioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtGrantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txtdisponibili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtPrecioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtPTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLimpiar)
                    .addComponent(BtnEliminar)
                    .addComponent(BtnModificar)
                    .addComponent(BtnIngresar)
                    .addComponent(BtnBuscar)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
        // TODO add your handling code here:
            if (TxtNumProducto.getText().equals("") || TxtNombreProducto.getText().equals("") || TxtCant.getText().equals("") || TxtDesc.getText().equals("") || TxtNumProducto.getText().equals("") || TxtImp.getText().equals("") /*|| TxtPrecioC.getText().equals("")*/ || TxtPrecioV.getText().equals("")||TxtPTotal.getText().equals("")||TxtPrecioC.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe insertar datos");
        } else {

            LNProducto logica = new LNProducto();
            Producto producto = GenerarEntidad();
            try {
                if((logica.VerificarIns(producto))==1){
                     JOptionPane.showMessageDialog(this, logica.getMensaje());
                }else{
                    logica.Insertar(producto);
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                }
                
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            try {
                CargarDatos("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

        
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void TblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblProductoMouseClicked
        // TODO add your handling code here:
        try {
            LNProducto logica = new LNProducto();
           Producto producto;
            String condicion;
            
            if(evt.getClickCount() == 2){
                int fila = TblProducto.rowAtPoint(evt.getPoint());
                TxtNumProducto.setText(TblProducto.getValueAt(fila, 0).toString());
                condicion = String.format("numero_producto = %s", TxtNumProducto.getText());
                producto = logica.ObtenerRegistro(condicion);
                
                TxtNumProducto.setText(String.valueOf(producto.getNumero_producto()));
                TxtNombreProducto.setText(producto.getNombre_producto());
                TxtTipoP.setSelectedItem(producto.getTipo_producto());
                TxtPrecioC.setText(Float.toString(producto.getPrecio_compra()));
                TxtPrecioV.setText(Float.toString(producto.getPrecio_venta()));
                TxtCant.setText(Integer.toString(producto.getCantidad()));
                TxtImp.setText(Float.toString(producto.getImpuesto()));
                TxtDesc.setText(Float.toString(producto.getDescuento()));
                TxtDescripcion.setText(producto.getDescripcion());
                TxtGrantia.setSelectedItem(producto.getGarantia());
                Txtdisponibili.setSelectedItem(producto.getDisponibilidad());
                TxtPTotal.setText(Float.toString(producto.getPrecio_total()));
                TxtNumProv.setText(Integer.toString(producto.getNum_proveedor()));
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_TblProductoMouseClicked

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
                    if (TxtNumProducto.getText().equals("") || TxtNombreProducto.getText().equals("") || TxtCant.getText().equals("") || TxtDesc.getText().equals("") || TxtNumProducto.getText().equals("") || TxtImp.getText().equals("") /*|| TxtPrecioC.getText().equals("")*/ || TxtPrecioV.getText().equals("")  ) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto para modificarlo");
        } else {

            LNProducto logica = new LNProducto();
            Producto producto = GenerarEntidad();
            try {
                if((logica.VerificarMod(producto))==1 || (logica.VerificarExiste(producto))==1){
                    JOptionPane.showMessageDialog(this, logica.getMensaje());
                }else{
                     logica.Modificar(producto);
                JOptionPane.showMessageDialog(this, logica.getMensaje());
                }
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            try {
                CargarDatos("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
                    if (TxtNumProducto.getText().equals("") || TxtNombreProducto.getText().equals("") || TxtCant.getText().equals("") || TxtDesc.getText().equals("") || TxtNumProducto.getText().equals("") || TxtImp.getText().equals("") /*|| TxtPrecioC.getText().equals("")*/ || TxtPrecioV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto para eliminarlo");
        } else {

            LNProducto logica = new LNProducto();
            Producto producto = GenerarEntidad();
            try {
                if((logica.VerificarProd(producto))==1 || (logica.VerificarExiste(producto))==1){
                     JOptionPane.showMessageDialog(this, logica.getMensaje());
                }else{
                      logica.Eliminar(producto);
                 JOptionPane.showMessageDialog(this, logica.getMensaje());
               
                }
              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            try {
                CargarDatos("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        FrmBuscarProducto buscar = new FrmBuscarProducto(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    LNProducto logica = new LNProducto();
                    Producto producto;
                    if (id > -1) {
                        condicion = String.format("numero_producto = %s", id);
                        producto = logica.ObtenerRegistro(condicion);

                        TxtNumProducto.setText(String.valueOf(producto.getNumero_producto()));
                        TxtNombreProducto.setText(producto.getNombre_producto());
                        TxtTipoP.setSelectedItem(producto.getTipo_producto());
                        TxtPrecioC.setText(Float.toString(producto.getPrecio_compra()));
                        TxtPrecioV.setText(Float.toString(producto.getPrecio_venta()));
                        TxtCant.setText(Integer.toString(producto.getCantidad()));
                        TxtImp.setText(Float.toString(producto.getImpuesto()));
                        TxtDesc.setText(Float.toString(producto.getDescuento()));
                        TxtDescripcion.setText(producto.getDescripcion());
                        TxtGrantia.setSelectedItem(producto.getGarantia());
                        Txtdisponibili.setSelectedItem(producto.getDisponibilidad());
                        TxtPTotal.setText(Float.toString(producto.getPrecio_total()));
                        TxtNumProv.setText(Integer.toString(producto.getNum_proveedor()));
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
       buscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void TxtNumProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumProductoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtNumProductoKeyTyped

    private void TxtNombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreProductoKeyTyped
        // TODO add your handling code here:
        SoloLetras(evt);
    }//GEN-LAST:event_TxtNombreProductoKeyTyped

    private void TxtNumProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumProvKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if( c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtNumProvKeyTyped

    private void TxtPrecioCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioCKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
          if( c<'0' || c > '9' ) evt.consume();
    }//GEN-LAST:event_TxtPrecioCKeyTyped

    private void TxtPrecioVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioVKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if( c<'0' || c > '9' ) evt.consume();
       
        //String precioV = TxtPrecioV.getText();
     
       
        
    }//GEN-LAST:event_TxtPrecioVKeyTyped

    private void TxtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCantKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if( c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtCantKeyTyped

    private void TxtImpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtImpKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if( c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtImpKeyTyped

    private void TxtDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDescKeyTyped
        // TODO add your handling code here:
//        char c = evt.getKeyChar();
//        if( c<'0' || c > '9') evt.consume();
  char c = evt.getKeyChar();
        if( c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtDescKeyTyped

    private void TxtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDescripcionKeyTyped
        // TODO add your handling code here:
        //SoloLetras(evt);
    }//GEN-LAST:event_TxtDescripcionKeyTyped

    private void TxtDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDescKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_TxtDescKeyPressed

    private void BtnBuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarProvActionPerformed
        // TODO add your handling code here:
         FrmBuscarProveedor buscar = new FrmBuscarProveedor(null, true);
        buscar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                try {
                    int id = buscar.ObtenerId();
                    String condicion = "";
                    LNProovedor logica = new LNProovedor();
                    Proveedor proveedor;
                    if (id > -1) {
                        condicion = String.format("num_proveedor = %s", id);
                        proveedor = logica.ObtenerRegistro(condicion);
                        
                        TxtNumProv.setText(Integer.toString(proveedor.getNum_proveedor()));
                    } else {
                        Limpiar();
                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        });
       buscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarProvActionPerformed

    private void TxtPrecioVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPrecioVMouseEntered
        // TODO add your handling code here:
    
       
    }//GEN-LAST:event_TxtPrecioVMouseEntered

    private void TxtPrecioVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrecioVActionPerformed
        // TODO add your handling code here:
//               try {
//         Float precioV = Float.parseFloat(TxtPrecioV.getText());
//        int descuento1 = 3;
//        if(precioV == 1000){
//            
//            TxtDesc.setText(""+ descuento1);
//        }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
        
    }//GEN-LAST:event_TxtPrecioVActionPerformed

    private void TxtPrecioVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPrecioVMouseExited
        // TODO add your handling code here:
//               try {
//         Float precioV = Float.parseFloat(TxtPrecioV.getText());
//        int descuento1 = 3;
//        if(precioV == 1000){
//            
//            TxtDesc.setText(""+ descuento1);
//        }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
        
    }//GEN-LAST:event_TxtPrecioVMouseExited

    private void TxtPrecioVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPrecioVMousePressed
        // TODO add your handling code here:
//                    try {
//         Float precioV = Float.parseFloat(TxtPrecioV.getText());
//        int descuento1 = 3;
//        if(precioV == 1000){
//            
//            TxtDesc.setText(""+ descuento1);
//        }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
    }//GEN-LAST:event_TxtPrecioVMousePressed

    private void TxtPrecioVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPrecioVMouseReleased
        // TODO add your handling code here:
//                            try {
//         Float precioV = Float.parseFloat(TxtPrecioV.getText());
//        int descuento1 = 3;
//        if(precioV == 1000){
//            
//            TxtDesc.setText(""+ descuento1);
//        }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
        
    }//GEN-LAST:event_TxtPrecioVMouseReleased

    private void TxtPrecioVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioVKeyPressed
        // TODO add your handling code here:
//                               try {
//         Float precioV = Float.parseFloat(TxtPrecioV.getText());
//        int descuento1 = 3;
//        if(precioV == 1000){
//            
//            TxtDesc.setText(""+ descuento1);
//        }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
    }//GEN-LAST:event_TxtPrecioVKeyPressed

    private void TxtPrecioVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioVKeyReleased
        // TODO add your handling code here:
        try {
            Float precioV = Float.parseFloat(TxtPrecioV.getText());
            float descuento1 = 2;
            float descuento2 = 3;
            float descuento3 = 5;
            float descuentoNull = 0;
            if (precioV >= 10000 && precioV <= 19999) {

                TxtDesc.setText("" + descuento1);
            } else if (precioV >= 20000 && precioV <= 39999) {
                TxtDesc.setText("" + descuento2);
            } else if (precioV >= 40000) {
                TxtDesc.setText("" + descuento3);
            } else {
                TxtDesc.setText("" + descuentoNull);
            }
            
            calcularPrecioTotal();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe llenar este campo");
        }
    }//GEN-LAST:event_TxtPrecioVKeyReleased

    private void TxtGrantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGrantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtGrantiaActionPerformed

    private void TxtPTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPTotalKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if( c<'0' || c > '9') evt.consume();
    }//GEN-LAST:event_TxtPTotalKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    void calcularPrecioTotal(){
        float prec= Float.parseFloat(TxtPrecioV.getText());
        float desc = Float.parseFloat(TxtDesc.getText());
        float imp = Float.parseFloat(TxtImp.getText());
        float total =0;
        float subt =0;
        float mDesc =0;
        
        subt = (prec*imp)/100+(prec); 
        mDesc = (subt*desc)/100;
        total = subt -mDesc;
        TxtPTotal.setText("" + total);
        if (total >= 30000 ){
            TxtGrantia.setSelectedIndex(0);
        }
        else{
            TxtGrantia.setSelectedIndex(1);
        }
        
    }
    
//      FrmBuscarProveedor buscar = new FrmBuscarProveedor(null, true);
//        buscar.addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosed(WindowEvent e) {
//                try {
//                    int id = buscar.ObtenerId();
//                    String condicion = "";
//                    LNProducto logica = new LNProducto();
//                    Producto producto;
//                    if (id > -1) {
//                        condicion = String.format("num_proveedor = %s", id);
//                        producto = logica.ObtenerRegistro(condicion);
//                        
//                        TxtNumProv.setText(Integer.toString(producto.getNum_proveedor()));
//                    } else {
//                        Limpiar();
//                    }
//                } catch (Exception ex) {
//                    JOptionPane.showMessageDialog(null, ex.getMessage());
//                }
//            }
//        });
//       buscar.setVisible(true);
    
    
    /**
     * @param args the command line arguments
     */
    
     public FrmProducto() {
        initComponents();
           try {
               float imp = 13;
            CargarDatos("");
            TxtImp.setText(""+ imp);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }
     
     /////////////
//      char c = evt.getKeyChar();
//      if( (c<'0' || c > '9') && (c!='.') ) evt.consume();
     ////////////
     
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }
    
    
//     char c = evt.getKeyChar();
//        if(c<'0' || c > '9') evt.consume();
    
    
     public void SoloLetras(KeyEvent evt){
        char s;
        s= evt.getKeyChar();
        if(!Character.isLetter(s) && s != KeyEvent.VK_SPACE ){
            evt.consume();
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnBuscarProv;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JTable TblProducto;
    private javax.swing.JTextField TxtCant;
    private javax.swing.JTextField TxtDesc;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JComboBox<String> TxtGrantia;
    private javax.swing.JTextField TxtImp;
    private javax.swing.JTextField TxtNombreProducto;
    private javax.swing.JTextField TxtNumProducto;
    private javax.swing.JTextField TxtNumProv;
    private javax.swing.JTextField TxtPTotal;
    private javax.swing.JTextField TxtPrecioC;
    private javax.swing.JTextField TxtPrecioV;
    private javax.swing.JComboBox<String> TxtTipoP;
    private javax.swing.JComboBox<String> Txtdisponibili;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
